### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bark/text_2.pt'

### ISSUE THREAD

**Issue by AlexandreBourrieau** [Mercity-AI/Voice-Cloning-Demo#1]
Hello,
After : 
`model.load_checkpoint(config, checkpoint_dir="bark/", eval=True)
`
I got "FileNotFoundError: [Errno 2] No such file or directory: 'bark/text_2.pt'"... Can you give me some advice ? Thanks !

**Comment by MathavanSG** [comment]
Hey @AlexandreBourrieau  You need to clone the repository of bark  from https://github.com/suno-ai/bark  once your done with it you will have the necessary tensors files while i was doing the project there was a minor bug in bark repo where the tensors files were downloaded as html format therefore i deleted the error tensor files and downloaded manually and replaced them in necessary directory where u have bark. you can download those files from https://huggingface.co/suno/bark/tree/main

**Comment by AlexandreBourrieau** [comment]
Thanks 👍
